# Generated by Django 6.0.1 on 2026-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
